DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  price INTEGER  NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  product_photo VARCHAR(255) NOT NULL,
  posted_date TIMESTAMP,
  sold BOOLEAN NOT NULL DEFAULT FALSE
);
