DROP TABLE IF EXISTS chats CASCADE;

CREATE TABLE chats (
  id SERIAL PRIMARY KEY NOT NULL,
  user_one INTEGER REFERENCES users(id) ON DELETE CASCADE,
  user_two INTEGER REFERENCES users(id) ON DELETE CASCADE,
  chat_created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
